name: 'Module Release'

on:
  workflow_call:
    inputs:
      ref:
        description: 'The git ref to checkout'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GH_TOKEN }}
      
      - name: ls
        run: ls -la
      - name: pwd
        run: pwd
      - name: asdf
        run: cd .. && ls -la

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
          branches: '[{"name": "main"}]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCHES: '["main"]'

