name: Generate Terraform Docs

on:
  workflow_call:
    inputs:
      ref:
        description: 'The git ref to checkout'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  generateDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout terraform-workflows repository for config files
        uses: actions/checkout@v4
        with:
          repository: nimisha-gj/terraform-workflows
          path: terraform-workflows
          token: ${{ secrets.GH_TOKEN }}

      - name: Render and Push terraform docs for main and modules
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          git-push: true
          config-file: terraform-workflows/.github/.terraform-docs.yaml

      - name: Render and Push terraform docs for examples
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ./examples
          git-push: true
          config-file: terraform-workflows/.github/.terraform-docs-example.yaml
